### ISSUE TITLE
`lib` as module name?

### ISSUE THREAD

**Issue by joerick** [stdlib/lib-python#1]
Hello! Really interested in what you guys are doing with stdlib.

Just for the record - I'm a little concerned about the module name `lib`. I think [a lot of developers](https://github.com/search?l=&p=4&q=from+lib+extension%3Apy&ref=advsearch&type=Code&utf8=%E2%9C%93) use that as an internal module name, so it might be a problem.

I'm guessing you guys have thought about this, so just wondering what your thoughts are on this and if it's up for debate?

**Comment by keithwhor** [comment]
Awesome! Thank you.

The number one goal here is to create as consistent of a developer experience as possible across languages. It's totally OK if developers have used it as a namespace in previous projects --- it's expected. In that case, they're welcome to use `from lib import lib as stdlib`, or something of the sort. :)
